### ISSUE TITLE
Receiving funds from binance 

### ISSUE THREAD

**Issue by Flexcoin** [fujicoin/fujicoin#1]
I downloaded both wallets to my laptop but it still says unconfirmed even though on the internet when I search the block address it says it's successful & all the confirmations have been recorded. And I can't seem to send out any coins/funds thank you

**Comment by fujicoin** [comment]
It will take about 2 days to synchronize to the network. Please keep wallet running and wait until synchronization is completed.

**Comment by Flexcoin** [comment]
I see , thank you so much ; Fuji coin is amazing !!
