### ISSUE TITLE
Unable to Remotely RPC Fujicoin from Another Server

### ISSUE THREAD

**Issue by daygle** [fujicoin/fujicoin#1]
Hi,

I am after your assistance in relation to an issue I have encountered with Fujicoin. I have setup a Fujicoin wallet on a remote Debian server and wanted to remotely connect to the wallet from another Debian server.

On the Fujicoin wallet server I have added the relevant rpcallowip=##IP Address## to the conf file and unfortunately the other server is unable to connect. I have other wallets that are able to connect the same way.

Has this functionality been removed? Has rpcallowip been setup to disallow remote connections from other servers? Do you have any other recommendations on how to make this work (to allow a remote server to connect to the Fujicoin wallet server).

Look forward to your reply.

**Comment by fujicoin** [comment]
Hi daygle,

The specification of `rpcallowip` has changed since version 0.18.0. See the "Configuration option changes" section in the release notes below.
https://bitcoincore.org/en/releases/0.18.0/
